language: python
python:
- "2.7"
- '3.6'
install:
- pip install .
- pip install -r requirements.txt
- pip install pyflakes
- pip install coveralls
before_script:
- if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then make pyflakes-27; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then make pyflakes; fi
script:
- if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then make test-27; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then make test; fi
- make coverage
after_success:
  coveralls
