language: python
python:
  - "2.7"
  - '3.6'
install:
- pip install .
- pip install -r requirements.txt
- pip install pyflakes
- pip install coveralls
before_script:
- make pyflakes
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then make test-2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then make test-3; fi
- make coverage
after_success:
  coveralls